### ISSUE TITLE
j/k scrolling broken on pinafore.social

### ISSUE THREAD

**Issue by LinuxMercedes** [cmcaine/tridactyl#372]
Certain sites, including pinafore.social (seems to be the case for mostly javascript-heavy ones) can't be scrolled with j/k even when I can scroll them with the arrow keys, spacebar, PgUp/PgDn, etc. Not really sure how to go about diagnosing this, but if you point me in the right direction I'll take a stab at diagnosing the problem!

**Comment by glacambre** [comment]
This issue is probably related to one of these: https://github.com/cmcaine/tridactyl/issues/273 https://github.com/cmcaine/tridactyl/issues/218 https://github.com/cmcaine/tridactyl/issues/107 https://github.com/cmcaine/tridactyl/issues/63 https://github.com/cmcaine/tridactyl/issues/35 .
I don't really know what could be done to fix this. Cmcaine mentions porting Vimperator's scrolling logic in https://github.com/cmcaine/tridactyl/issues/218 , maybe this is the way to go.

**Comment by glacambre** [comment]
Hi, could you test whether https://github.com/cmcaine/tridactyl/pull/318 fixes this issue? I don't have an account on pinafore.social :)

**Comment by bovine3dom** [comment]
@LinuxMercedes there's a small possibility that this is fixed in the latest betas, which include #318.

Just go to https://tridactyl.cmcaine.co.uk/betas/?sort=time&order=desc and choose the first one.

**Comment by LinuxMercedes** [comment]
@glacambre @bovine3dom Tridactyl 1.8.2-64-g87574e0 does not seem to fix this problem; both j/k and :scrollpx 0 10 do not scroll the site.

**Comment by bovine3dom** [comment]
Likely fixed in 15c8c47 - would you mind checking again, @LinuxMercedes?

**Comment by LinuxMercedes** [comment]
Yep, that fixed it! Thanks so much!
