### ISSUE TITLE
URL pop-up when hovering on link covers up command line

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#40]
Really annoying on link dense pages like https://news.bbc.co.uk.

**Comment by bovine3dom** [comment]
URL pop-ups are hidden in e01d34a (via userChrome) but I'd rather we had a solution for all users, if at all possible.

**Comment by KrazyCavin** [comment]
Thanks for the inspiration. It's a nice trick to hide it.
Sometimes, URL hint is helpful for me. So I changed userChrome.css to move it to top-left. It feels good now.

**Comment by qoxxxx** [comment]
@krazycavin, would you mind sharing how ? Thanks.

**Comment by KrazyCavin** [comment]
@qoxxxx It't my dumb way, don't mock me
```
statuspanel[type="overLink"]{
        top:54px;
}
```
Put this in userChrome.css

**Comment by joelpet** [comment]
I made the following amendment to @KrazyCavin's suggestion:

```css
statuspanel[type="overLink"] .statuspanel-label {
    border-width: 0 1px 1px 0 !important;
    border-color: rgb(182, 182, 179) !important;
    border-style: solid !important;
}
```

**Comment by bovine3dom** [comment]
`guiset hoverlink [none|left|right|topleft|topright]` in Tridactyl 1.11.0+, if you have the native messenger installed. (Requires a restart).

**Comment by krigstask** [comment]
For others who find this in Google: it's **top-left|top-right** now (note the hyphen).

**Comment by bovine3dom** [comment]
Fixed in my comment : )

**Comment by hemanti0503** [comment]
> `guiset hoverlink [none|left|right|top-left|top-right]` in Tridactyl 1.11.0+, if you have the native messenger installed. (Requires a restart).

Doesn't work for me in newest beta. I tried both top-right and right, restarted Firefox both times - but both times the hovering links are still shown in left-bottom corner, covering Tridactyl command line. I have native messenger installed.

**Comment by skrattaren** [comment]
The workaround I went for in the end is to switch to a theme with command line in the middle of the window, like `midnight`.

**Comment by hemanti0503** [comment]
Thanks for that proposal! However, I quite like the standard design. Shouldn't the `guiset hoverlink` commands "just work", or did I get anything wrong?

**Comment by bovine3dom** [comment]
I'm reluctant to fix bugs that appear in Firefox beta because maybe half the time Mozilla fixes them before they make it to stable :)

In theory this shouldn't matter though as whenever you open the command line the currently active hoverlink should get hidden. Can you confirm whether this is the case?

**Comment by hemanti0503** [comment]
I'm not on Firefox beta. I'm running 95.0.1 as shipped with Linux Mint.

Indeed, now the command line hides the active hoverlink. No idea, why this didn't happen before. Perhaps had something to do with my trackpoint sometimes moving on its own. I'll let you know once the issue re-appears.

**Comment by hemanti0503** [comment]
I found, that this is indeed a different issue. It is not the links on a page, that cover Tridactyl when hovering them, but links inside Tridactyl itself (history of opened URLs when doing `:tabopen`, e.g.).

Let's say, I type `:tabopen` and then hover the mouse over a link in Tridactyl's history. Its URL will then permanently cover the command line. This even continues if I narrow down the search results (by typing a few words), so that the list reduces to none or only a few entries. Now, the mouse won't hover any link anymore, but the last hovered link still covers the command line.

Can you understand what I mean? Can you reproduce?

**Comment by bovine3dom** [comment]
@hemanti0503 thanks, I can confirm that. I made a new issue for it.

`:guiset` does still work for me though in Firefox 95. Are you sure `:native` is working?

**Comment by hemanti0503** [comment]
Yeah, it is working. I just performed `guiset hoverlink top-right` again and restarted Firefox. I don't see any difference in behavior, though. Just to make sure: It should show those links when I hover over a link in the upper-right part of Firefox, right?

Perhaps, it has something to do with me tweaking my chrome.css manually to remove the tab-close buttons from the tabs on the tab bar?! In an empty profile I get `Error: native.ts:getProfile() : '-P' found in command line arguments but no matching profile name found in "/home/user/.mozilla/firefox/profiles.ini"`

**Comment by hemanti0503** [comment]
Actually, it is working now. Perhaps, it just needed some time.

**Comment by bovine3dom** [comment]
You have to restart Firefox twice (!) for guiset to take effect usually, so maybe that was the problem.

The profile thing sounds like it needs a new issue opening really if you can provide more details :)

**Comment by bovine3dom** [comment]
possible they've broken it again. how do you feel about `:colours quakelight` as a workaround?

**Comment by bo0ts** [comment]
A blast from the past. That will do. Thank you!
